# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Capacity.proto

require 'google/protobuf'


descriptor_data = "\n\x0e\x43\x61pacity.proto\x12\x07\x65xample\"G\n\x08\x43\x61pacity\x12\x11\n\tserver_id\x18\x01 \x01(\x05\x12\x15\n\rserver_status\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Example
  Capacity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.Capacity").msgclass
end
