# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/main/proto/Configuration.proto

require 'google/protobuf'


descriptor_data = "\n\"src/main/proto/Configuration.proto\x12\x07\x65xample\">\n\rConfiguration\x12\x1d\n\x15\x66\x61ult_tolerance_level\x18\x01 \x01(\x05\x12\x0e\n\x06method\x18\x02 \x01(\tb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Example
  Configuration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.Configuration").msgclass
end
