// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/Subscriber.proto
// Protobuf Java Version: 4.28.3

package example;

public final class SubscriberOuterClass {
  private SubscriberOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      SubscriberOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubscriberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.Subscriber)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * SUBS, ONLN, OFFL
     * </pre>
     *
     * <code>string status = 1;</code>
     * @return The status.
     */
    java.lang.String getStatus();
    /**
     * <pre>
     * SUBS, ONLN, OFFL
     * </pre>
     *
     * <code>string status = 1;</code>
     * @return The bytes for status.
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <pre>
     * Kullanıcı adı ve soyadı
     * </pre>
     *
     * <code>string name_surname = 2;</code>
     * @return The nameSurname.
     */
    java.lang.String getNameSurname();
    /**
     * <pre>
     * Kullanıcı adı ve soyadı
     * </pre>
     *
     * <code>string name_surname = 2;</code>
     * @return The bytes for nameSurname.
     */
    com.google.protobuf.ByteString
        getNameSurnameBytes();

    /**
     * <pre>
     * Sistem tarafından atanacak ID
     * </pre>
     *
     * <code>int32 id = 3;</code>
     * @return The id.
     */
    int getId();

    /**
     * <pre>
     * UNIX zaman damgası
     * </pre>
     *
     * <code>int64 last_accessed = 4;</code>
     * @return The lastAccessed.
     */
    long getLastAccessed();
  }
  /**
   * Protobuf type {@code example.Subscriber}
   */
  public static final class Subscriber extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:example.Subscriber)
      SubscriberOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        Subscriber.class.getName());
    }
    // Use Subscriber.newBuilder() to construct.
    private Subscriber(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Subscriber() {
      status_ = "";
      nameSurname_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return example.SubscriberOuterClass.internal_static_example_Subscriber_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return example.SubscriberOuterClass.internal_static_example_Subscriber_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              example.SubscriberOuterClass.Subscriber.class, example.SubscriberOuterClass.Subscriber.Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object status_ = "";
    /**
     * <pre>
     * SUBS, ONLN, OFFL
     * </pre>
     *
     * <code>string status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * SUBS, ONLN, OFFL
     * </pre>
     *
     * <code>string status = 1;</code>
     * @return The bytes for status.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_SURNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nameSurname_ = "";
    /**
     * <pre>
     * Kullanıcı adı ve soyadı
     * </pre>
     *
     * <code>string name_surname = 2;</code>
     * @return The nameSurname.
     */
    @java.lang.Override
    public java.lang.String getNameSurname() {
      java.lang.Object ref = nameSurname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nameSurname_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Kullanıcı adı ve soyadı
     * </pre>
     *
     * <code>string name_surname = 2;</code>
     * @return The bytes for nameSurname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameSurnameBytes() {
      java.lang.Object ref = nameSurname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nameSurname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 3;
    private int id_ = 0;
    /**
     * <pre>
     * Sistem tarafından atanacak ID
     * </pre>
     *
     * <code>int32 id = 3;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int LAST_ACCESSED_FIELD_NUMBER = 4;
    private long lastAccessed_ = 0L;
    /**
     * <pre>
     * UNIX zaman damgası
     * </pre>
     *
     * <code>int64 last_accessed = 4;</code>
     * @return The lastAccessed.
     */
    @java.lang.Override
    public long getLastAccessed() {
      return lastAccessed_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, status_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nameSurname_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, nameSurname_);
      }
      if (id_ != 0) {
        output.writeInt32(3, id_);
      }
      if (lastAccessed_ != 0L) {
        output.writeInt64(4, lastAccessed_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, status_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nameSurname_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, nameSurname_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, id_);
      }
      if (lastAccessed_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, lastAccessed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof example.SubscriberOuterClass.Subscriber)) {
        return super.equals(obj);
      }
      example.SubscriberOuterClass.Subscriber other = (example.SubscriberOuterClass.Subscriber) obj;

      if (!getStatus()
          .equals(other.getStatus())) return false;
      if (!getNameSurname()
          .equals(other.getNameSurname())) return false;
      if (getId()
          != other.getId()) return false;
      if (getLastAccessed()
          != other.getLastAccessed()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (37 * hash) + NAME_SURNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNameSurname().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + LAST_ACCESSED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastAccessed());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static example.SubscriberOuterClass.Subscriber parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.SubscriberOuterClass.Subscriber parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.SubscriberOuterClass.Subscriber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.SubscriberOuterClass.Subscriber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.SubscriberOuterClass.Subscriber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.SubscriberOuterClass.Subscriber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.SubscriberOuterClass.Subscriber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static example.SubscriberOuterClass.Subscriber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static example.SubscriberOuterClass.Subscriber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static example.SubscriberOuterClass.Subscriber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static example.SubscriberOuterClass.Subscriber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static example.SubscriberOuterClass.Subscriber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(example.SubscriberOuterClass.Subscriber prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.Subscriber}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.Subscriber)
        example.SubscriberOuterClass.SubscriberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return example.SubscriberOuterClass.internal_static_example_Subscriber_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return example.SubscriberOuterClass.internal_static_example_Subscriber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                example.SubscriberOuterClass.Subscriber.class, example.SubscriberOuterClass.Subscriber.Builder.class);
      }

      // Construct using example.SubscriberOuterClass.Subscriber.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        status_ = "";
        nameSurname_ = "";
        id_ = 0;
        lastAccessed_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return example.SubscriberOuterClass.internal_static_example_Subscriber_descriptor;
      }

      @java.lang.Override
      public example.SubscriberOuterClass.Subscriber getDefaultInstanceForType() {
        return example.SubscriberOuterClass.Subscriber.getDefaultInstance();
      }

      @java.lang.Override
      public example.SubscriberOuterClass.Subscriber build() {
        example.SubscriberOuterClass.Subscriber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public example.SubscriberOuterClass.Subscriber buildPartial() {
        example.SubscriberOuterClass.Subscriber result = new example.SubscriberOuterClass.Subscriber(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(example.SubscriberOuterClass.Subscriber result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.status_ = status_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.nameSurname_ = nameSurname_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.lastAccessed_ = lastAccessed_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof example.SubscriberOuterClass.Subscriber) {
          return mergeFrom((example.SubscriberOuterClass.Subscriber)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(example.SubscriberOuterClass.Subscriber other) {
        if (other == example.SubscriberOuterClass.Subscriber.getDefaultInstance()) return this;
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getNameSurname().isEmpty()) {
          nameSurname_ = other.nameSurname_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getLastAccessed() != 0L) {
          setLastAccessed(other.getLastAccessed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                status_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                nameSurname_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                lastAccessed_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object status_ = "";
      /**
       * <pre>
       * SUBS, ONLN, OFFL
       * </pre>
       *
       * <code>string status = 1;</code>
       * @return The status.
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * SUBS, ONLN, OFFL
       * </pre>
       *
       * <code>string status = 1;</code>
       * @return The bytes for status.
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * SUBS, ONLN, OFFL
       * </pre>
       *
       * <code>string status = 1;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        status_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * SUBS, ONLN, OFFL
       * </pre>
       *
       * <code>string status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        status_ = getDefaultInstance().getStatus();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * SUBS, ONLN, OFFL
       * </pre>
       *
       * <code>string status = 1;</code>
       * @param value The bytes for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        status_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object nameSurname_ = "";
      /**
       * <pre>
       * Kullanıcı adı ve soyadı
       * </pre>
       *
       * <code>string name_surname = 2;</code>
       * @return The nameSurname.
       */
      public java.lang.String getNameSurname() {
        java.lang.Object ref = nameSurname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nameSurname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Kullanıcı adı ve soyadı
       * </pre>
       *
       * <code>string name_surname = 2;</code>
       * @return The bytes for nameSurname.
       */
      public com.google.protobuf.ByteString
          getNameSurnameBytes() {
        java.lang.Object ref = nameSurname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nameSurname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Kullanıcı adı ve soyadı
       * </pre>
       *
       * <code>string name_surname = 2;</code>
       * @param value The nameSurname to set.
       * @return This builder for chaining.
       */
      public Builder setNameSurname(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nameSurname_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Kullanıcı adı ve soyadı
       * </pre>
       *
       * <code>string name_surname = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNameSurname() {
        nameSurname_ = getDefaultInstance().getNameSurname();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Kullanıcı adı ve soyadı
       * </pre>
       *
       * <code>string name_surname = 2;</code>
       * @param value The bytes for nameSurname to set.
       * @return This builder for chaining.
       */
      public Builder setNameSurnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nameSurname_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       * Sistem tarafından atanacak ID
       * </pre>
       *
       * <code>int32 id = 3;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       * Sistem tarafından atanacak ID
       * </pre>
       *
       * <code>int32 id = 3;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Sistem tarafından atanacak ID
       * </pre>
       *
       * <code>int32 id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        id_ = 0;
        onChanged();
        return this;
      }

      private long lastAccessed_ ;
      /**
       * <pre>
       * UNIX zaman damgası
       * </pre>
       *
       * <code>int64 last_accessed = 4;</code>
       * @return The lastAccessed.
       */
      @java.lang.Override
      public long getLastAccessed() {
        return lastAccessed_;
      }
      /**
       * <pre>
       * UNIX zaman damgası
       * </pre>
       *
       * <code>int64 last_accessed = 4;</code>
       * @param value The lastAccessed to set.
       * @return This builder for chaining.
       */
      public Builder setLastAccessed(long value) {

        lastAccessed_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * UNIX zaman damgası
       * </pre>
       *
       * <code>int64 last_accessed = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastAccessed() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lastAccessed_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:example.Subscriber)
    }

    // @@protoc_insertion_point(class_scope:example.Subscriber)
    private static final example.SubscriberOuterClass.Subscriber DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new example.SubscriberOuterClass.Subscriber();
    }

    public static example.SubscriberOuterClass.Subscriber getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Subscriber>
        PARSER = new com.google.protobuf.AbstractParser<Subscriber>() {
      @java.lang.Override
      public Subscriber parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Subscriber> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Subscriber> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public example.SubscriberOuterClass.Subscriber getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_Subscriber_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_example_Subscriber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037src/main/proto/Subscriber.proto\022\007examp" +
      "le\"U\n\nSubscriber\022\016\n\006status\030\001 \001(\t\022\024\n\014name" +
      "_surname\030\002 \001(\t\022\n\n\002id\030\003 \001(\005\022\025\n\rlast_acces" +
      "sed\030\004 \001(\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_example_Subscriber_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_example_Subscriber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_example_Subscriber_descriptor,
        new java.lang.String[] { "Status", "NameSurname", "Id", "LastAccessed", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
